# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mjYlBtUYIy6CQlYXYQqX4EA_ijAb8x0X
"""

import streamlit as st
import pandas as pd
from google import genai
from data_pipeline import run_pipeline_universal

st.set_page_config(page_title="Clean Data, Explained", page_icon="🧹", layout="centered")
st.title("🧹 Clean Data, Explained")
st.caption("Upload any CSV. Get a cleaned file and a plain-English report of every issue found.")

# --- Gemini connection ---
client = genai.Client(api_key=st.secrets["Gemini_Key"])
MODEL = "gemini-3.6-flash"

# --- Upload interface ---
uploaded = st.file_uploader("Upload your CSV", type="csv")
use_sample = st.button("...or use the sample dataset")

raw_df = None
if uploaded:
    raw_df = pd.read_csv(uploaded)
elif use_sample:
    raw_df = pd.read_csv("orders_dirty.csv")

# --- Run pipeline and show results ---
if raw_df is not None:
    with st.spinner("Analyzing your data and generating a report..."):
        try:
            clean_df, issues_df, stats, schema_info = run_pipeline_universal(
                raw_df, client=client, model=MODEL
            )

            col1, col2, col3 = st.columns(3)
            col1.metric("Rows before", stats["rows_before"])
            col2.metric("Rows after", stats["rows_after"])
            col3.metric("Issues flagged", stats["total_issues_flagged"])

            with st.expander("How this file was understood"):
                st.write(f"**Deduplication method:** {stats['dedupe_method']}")
                st.write("**Detected column types:**")
                st.json(stats["detected_column_types"])
                if stats["ai_suggested_checks"]:
                    st.write("**AI-suggested business rules checked:**")
                    for c in stats["ai_suggested_checks"]:
                        st.write(f"- `{c['column_a']} {c['operator']} {c['column_b']}` — {c['reason']}")
                else:
                    st.write("No cross-column business rules were suggested for this file.")

            st.subheader("Data Quality Report")
            if len(issues_df) == 0:
                st.success("No issues found — data looks clean!")
            else:
                for category, group in issues_df.groupby("category"):
                    with st.expander(f"{category} — {len(group)} rows affected"):
                        st.dataframe(group.head(10))

            st.subheader("Download")
            st.download_button("Download cleaned CSV", clean_df.to_csv(index=False), "cleaned_data.csv")
            st.download_button("Download issues detail CSV", issues_df.to_csv(index=False), "issues_detail.csv")

        except Exception as e:
            st.error(f"Something went wrong processing this file: {e}")
            st.info("Try a different file, or check that it's a standard CSV with a header row.")

st.divider()
st.caption("This tool auto-detects column types and business rules — try it on any transactional or tabular CSV.")