# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mjYlBtUYIy6CQlYXYQqX4EA_ijAb8x0X
"""

import streamlit as st
import pandas as pd
from google import genai
from google.genai import types
from pipeline import run_pipeline

st.set_page_config(page_title="Clean Data, Explained", page_icon="🧹", layout="centered")
st.title("🧹 Clean Data, Explained")
st.caption("Upload a messy CSV. Get a cleaned file and a plain-English report of every issue found.")

#client = genai.Client(api_key=st.secrets["Gemini_Key"])
client = genai.Client(api_key=st.secrets["GEMINI_API_KEY"])
MODEL = "gemini-3.6-flash"

SYSTEM_PROMPT = """You are a senior data analyst writing a data quality report for a non-technical business stakeholder.
For each data issue category you're given, write:
1. A one-sentence plain-English explanation of what the issue is and why it likely happened.
2. A one-sentence recommended fix or process change to prevent it going forward.
Keep the tone professional, concise, and non-alarmist. Avoid technical jargon."""

def explain_category(category, count, sample_details):
    user_prompt = f"""Issue category: {category}
Number of rows affected: {count}
Example details:
{chr(10).join('- ' + d for d in sample_details[:5])}
Write the explanation and recommended fix as described."""
    response = client.models.generate_content(
        model=MODEL,
        contents=user_prompt,
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_PROMPT,
            temperature=0,
        ),
    )
    return response.text.strip()

uploaded = st.file_uploader("Upload your CSV", type="csv")
use_sample = st.button("...or use the sample dataset")

raw_df = None
if uploaded:
    raw_df = pd.read_csv(uploaded)
elif use_sample:
    raw_df = pd.read_csv("orders_dirty.csv")

if raw_df is not None:
    with st.spinner("Cleaning data and generating explanations..."):
        clean_df, issues_df, stats = run_pipeline(raw_df)

        col1, col2, col3 = st.columns(3)
        col1.metric("Rows before", stats["rows_before"])
        col2.metric("Rows after", stats["rows_after"])
        col3.metric("Issues flagged", stats["total_issues_flagged"])

        st.subheader("Data Quality Report")
        if len(issues_df) == 0:
            st.success("No issues found — data looks clean!")
        else:
            for category, group in issues_df.groupby("category"):
                with st.expander(f"{category} — {len(group)} rows affected"):
                    explanation = explain_category(category, len(group), group["detail"].tolist())
                    st.write(explanation)
                    st.dataframe(group.head(10))

        st.subheader("Download")
        st.download_button("Download cleaned CSV", clean_df.to_csv(index=False), "cleaned_data.csv")
        st.download_button("Download issues detail CSV", issues_df.to_csv(index=False), "issues_detail.csv")

st.divider()
st.caption("Tip: try uploading your own order/transaction CSV, or use the sample to see a demo run.")

