# -*- coding: utf-8 -*-
"""data_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VT1Q6X95k7B_6yWFaIAFv6CQDZ7eaOzX
"""

import pandas as pd
import numpy as np
import re
import json
from rapidfuzz import fuzz
from google.genai import types

VALID_ROLES = {"identifier", "name", "quantity", "monetary", "date", "category", "other"}

# ---------- Issue record helper ----------

def make_issue(row_index, category, severity, action, column, old_value, new_value, detail):
    """
    severity: 'error' | 'warning' | 'info'
    action:   'removed' | 'imputed' | 'standardized' | 'flagged' | 'ignored'
    """
    return {
        "row_index": row_index, "category": category, "severity": severity,
        "action": action, "column": column, "old_value": old_value,
        "new_value": new_value, "detail": detail,
    }

# ---------- Part A: column type detection ----------

def try_convert_to_numeric(series: pd.Series) -> tuple[pd.Series, bool]:
    cleaned = series.astype(str).str.replace(r"[$£€,]", "", regex=True).str.strip()
    converted = pd.to_numeric(cleaned, errors="coerce")
    non_null_original = series.notna().sum()
    if non_null_original == 0:
        return series, False
    return converted, (converted.notna().sum() / non_null_original) > 0.85


def try_convert_to_datetime(series: pd.Series) -> tuple[pd.Series, bool]:
    converted = pd.to_datetime(series, errors="coerce", format="mixed")
    non_null_original = series.notna().sum()
    if non_null_original == 0:
        return series, False
    return converted, (converted.notna().sum() / non_null_original) > 0.85


def infer_and_clean_types(df: pd.DataFrame) -> tuple[pd.DataFrame, dict]:
    df = df.copy()
    column_types = {}
    for col in df.columns:
        if pd.api.types.is_numeric_dtype(df[col]):
            column_types[col] = "numeric"
            continue
        if pd.api.types.is_datetime64_any_dtype(df[col]):
            column_types[col] = "datetime"
            continue
        numeric_attempt, is_numeric = try_convert_to_numeric(df[col])
        if is_numeric:
            df[col] = numeric_attempt
            column_types[col] = "numeric"
            continue
        datetime_attempt, is_datetime = try_convert_to_datetime(df[col])
        if is_datetime:
            df[col] = datetime_attempt
            column_types[col] = "datetime"
            continue
        column_types[col] = "text"
    return df, column_types

# ---------- Part B: semantic role inference (heuristic + optional AI override) ----------

def infer_semantic_roles(df: pd.DataFrame, column_types: dict, ai_column_roles: dict | None = None) -> dict:
    roles = {}
    for col in df.columns:
        name = col.lower()
        t = column_types.get(col)
        if re.search(r"(^id$|_id$|^id_|order_id|transaction_id|customer_id|product_id)", name):
            roles[col] = "identifier"
        elif "name" in name:
            roles[col] = "name"
        elif re.search(r"(qty|quantity)", name):
            roles[col] = "quantity"
        elif re.search(r"(price|amount|total|refund|cost|revenue)", name):
            roles[col] = "monetary"
        elif t == "datetime":
            roles[col] = "date"
        elif t == "text" and df[col].nunique() / max(len(df), 1) <= 0.5:
            roles[col] = "category"
        else:
            roles[col] = "other"

    # AI can override a heuristic guess, but only with a value from our fixed vocabulary —
    # this is the "Gemini suggests, Python validates" pattern applied to roles too.
    if ai_column_roles:
        for col, role in ai_column_roles.items():
            if col in roles and role in VALID_ROLES:
                roles[col] = role
    return roles

# ---------- Part C: safer deduplication ----------

def detect_id_column(df: pd.DataFrame) -> str | None:
    candidates = []
    for col in df.columns:
        uniqueness = df[col].nunique() / max(len(df), 1)
        name_hint = bool(re.search(r"(^id$|_id$|^id_|order|transaction|record)", col.lower()))
        if uniqueness > 0.95:
            candidates.append((col, uniqueness, name_hint))
    if not candidates:
        return None
    candidates.sort(key=lambda c: (c[2], c[1]), reverse=True)
    return candidates[0][0]


def deduplicate_universal(df: pd.DataFrame) -> tuple[pd.DataFrame, int, str, list[dict]]:
    """
    Prefers deduplicating on a detected ID column, but ONLY if every row sharing
    that ID is otherwise fully identical — if rows differ elsewhere (a real
    transaction-line dataset, e.g. same Order_ID with different Products), it
    falls back to exact full-row matching instead, so legitimate line items are
    never wrongly merged.
    """
    df = df.copy()
    id_col = detect_id_column(df)

    if id_col:
        dupe_groups = df[df.duplicated(subset=[id_col], keep=False)]
        safe = True
        if len(dupe_groups) > 0:
            for _, group in dupe_groups.groupby(id_col):
                if group.drop(columns=[id_col]).nunique(dropna=False).sum() > len(group.columns) - 1:
                    safe = False
                    break
        if safe:
            df2 = df.drop_duplicates(subset=[id_col], keep="first")
            method = f"deduplicated on ID column '{id_col}' (verified rows fully identical aside from ID)"
        else:
            df2 = df.drop_duplicates(keep="first")
            method = f"'{id_col}' looked like an ID but rows differ elsewhere (likely line items) — used exact full-row matching instead"
    else:
        df2 = df.drop_duplicates(keep="first")
        method = "deduplicated on exact full-row matches (no reliable single ID column found)"

    dropped_idx = df.index.difference(df2.index)
    issues = [
        make_issue(idx, "Duplicate Row", "error", "removed", None, None, None,
                   "Exact duplicate row removed")
        for idx in dropped_idx
    ]
    return df2, len(dropped_idx), method, issues

# ---------- Part D: categorical near-duplicate standardization (info-level, no removal) ----------

def find_near_duplicate_groups(values: list[str], threshold: int = 85) -> dict:
    unique_vals = list(set(str(v) for v in values if pd.notna(v)))
    groups, used = [], set()
    for val in unique_vals:
        if val in used:
            continue
        group = [val]
        used.add(val)
        for other in unique_vals:
            if other in used:
                continue
            if fuzz.ratio(val.lower(), other.lower()) >= threshold:
                group.append(other)
                used.add(other)
        groups.append(group)
    mapping = {}
    for group in groups:
        if len(group) > 1:
            canonical = max(group, key=len)
            for v in group:
                mapping[v] = canonical
    return mapping


def standardize_categoricals_universal(df: pd.DataFrame, column_types: dict) -> tuple[pd.DataFrame, list[dict]]:
    df = df.copy()
    issues = []
    text_cols = [c for c, t in column_types.items() if t == "text"]
    for col in text_cols:
        unique_count = df[col].nunique()
        if unique_count == 0 or unique_count / max(len(df), 1) > 0.5:
            continue  # likely free text (names), not a category column
        mapping = find_near_duplicate_groups(df[col].dropna().unique().tolist())
        if mapping:
            before_values = df[col].copy()
            df[col] = df[col].replace(mapping)
            changed_idx = df.index[df[col] != before_values]
            for idx in changed_idx:
                issues.append(make_issue(
                    idx, f"Standardized value in '{col}'", "info", "standardized", col,
                    before_values.at[idx], df.at[idx, col], "Merged near-duplicate category values"
                ))
    return df, issues

# ---------- Part E: missing-value policy ----------

def handle_missing_values(df: pd.DataFrame, roles: dict) -> tuple[pd.DataFrame, pd.Series, list[dict]]:
    """
    identifier/name/quantity/monetary + missing -> flagged for removal (unrecoverable)
    category + missing -> imputed with 'Not Provided' (info-level, never removed)
    date/other + missing -> left as-is (no action; not a hard requirement)
    """
    df = df.copy()
    remove_mask = pd.Series(False, index=df.index)
    issues = []

    for col, role in roles.items():
        missing = df[col].isna()
        if not missing.any():
            continue

        if role in ("identifier", "name", "quantity", "monetary"):
            remove_mask |= missing
            for idx in df[missing].index:
                issues.append(make_issue(
                    idx, "Missing Required Value", "error", "removed", col,
                    None, None, f"Required field '{col}' is missing"
                ))
        elif role == "category":
            for idx in df[missing].index:
                issues.append(make_issue(
                    idx, f"Missing Value Imputed in '{col}'", "info", "imputed", col,
                    None, "Not Provided", f"Optional field '{col}' was blank, filled with 'Not Provided'"
                ))
            df.loc[missing, col] = "Not Provided"
        # date/other: no action

    return df, remove_mask, issues

# ---------- Part F: deterministic domain rules ----------

def detect_domain_violations(df: pd.DataFrame, roles: dict) -> tuple[pd.Series, list[dict]]:
    """Quantity/monetary values below zero are invalid by definition, not by rarity."""
    remove_mask = pd.Series(False, index=df.index)
    issues = []
    for col, role in roles.items():
        if role not in ("quantity", "monetary"):
            continue
        if not pd.api.types.is_numeric_dtype(df[col]):
            continue
        violation = (df[col] < 0).fillna(False)
        remove_mask |= violation
        for idx in df[violation].index:
            issues.append(make_issue(
                idx, f"Negative value in '{col}'", "error", "removed", col,
                df.at[idx, col], None, f"'{col}' cannot be negative"
            ))
    return remove_mask, issues

# ---------- Part G: AI schema inspection (Gemini suggests; never edits data) ----------

SCHEMA_SYSTEM_PROMPT = """You are a data analyst inspecting an unfamiliar dataset.
You will be given column names, their detected data types, and a few sample rows.
Respond with ONLY valid JSON (no markdown, no explanation) in this exact structure:

{
  "column_roles": {"column_name": "one of: identifier, name, quantity, monetary, date, category, other"},
  "suggested_checks": [
    {"column_a": "...", "operator": "<=", "column_b": "...", "reason": "..."}
  ]
}

Rules:
- column_roles values MUST be exactly one of: identifier, name, quantity, monetary, date, category, other.
- Only suggest a check if both columns are numeric and the relationship is a genuine,
  common-sense business rule (e.g. a refund shouldn't exceed an order total).
- valid "operator" values: "<=", ">=", "<", ">"
- If nothing sensible applies, return an empty list for "suggested_checks".
- Keep "reason" to one short sentence.
"""


def inspect_schema(df: pd.DataFrame, column_types: dict, client, model: str) -> dict:
    sample_rows = df.head(3).to_dict(orient="records")
    user_prompt = f"""Columns and detected types:
{json.dumps(column_types, indent=2)}

Sample rows:
{json.dumps(sample_rows, indent=2, default=str)}
"""
    try:
        response = client.models.generate_content(
            model=model,
            contents=user_prompt,
            config=types.GenerateContentConfig(
                system_instruction=SCHEMA_SYSTEM_PROMPT,
                temperature=0,
                response_mime_type="application/json",
            ),
        )
        return json.loads(response.text)
    except Exception:
        return {"column_roles": {}, "suggested_checks": []}

# ---------- Part H: validate AND execute AI-suggested rules ----------

def validate_and_apply_ai_rules(df: pd.DataFrame, suggested_checks: list[dict]) -> tuple[pd.Series, list[dict]]:
    remove_mask = pd.Series(False, index=df.index)
    issues = []
    ops = {
        "<=": lambda a, b: a > b,
        ">=": lambda a, b: a < b,
        "<":  lambda a, b: a >= b,
        ">":  lambda a, b: a <= b,
    }
    for check in suggested_checks or []:
        col_a, col_b, op = check.get("column_a"), check.get("column_b"), check.get("operator")
        reason = check.get("reason", "")

        if col_a not in df.columns or col_b not in df.columns or op not in ops:
            issues.append(make_issue(
                None, "AI suggestion rejected", "info", "ignored", None, None, None,
                f"Rule '{col_a} {op} {col_b}' skipped: column(s) not found or invalid operator"
            ))
            continue
        if not pd.api.types.is_numeric_dtype(df[col_a]) or not pd.api.types.is_numeric_dtype(df[col_b]):
            issues.append(make_issue(
                None, "AI suggestion rejected", "info", "ignored", None, None, None,
                f"Rule '{col_a} {op} {col_b}' skipped: column(s) not numeric"
            ))
            continue

        violated = ops[op](df[col_a], df[col_b]).fillna(False)
        remove_mask |= violated
        for idx in df[violated].index:
            issues.append(make_issue(
                idx, f"Business rule violation: {col_a} {op} {col_b}", "error", "removed",
                f"{col_a}/{col_b}", f"{df.at[idx, col_a]}/{df.at[idx, col_b]}", None, reason
            ))
    return remove_mask, issues

# ---------- Part I: statistical anomalies (flag only — never removed by default) ----------

def detect_statistical_anomalies(df: pd.DataFrame, column_types: dict) -> list[dict]:
    issues = []
    numeric_cols = [c for c, t in column_types.items() if t == "numeric"]
    for col in numeric_cols:
        series = df[col].dropna()
        if len(series) < 10:
            continue
        q1, q3 = series.quantile([0.25, 0.75])
        iqr = q3 - q1
        if iqr == 0:
            continue
        upper_bound = q3 + 3 * iqr
        lower_bound = q1 - 3 * iqr
        mask = (df[col] > upper_bound) | (df[col] < lower_bound)
        for idx in df[mask].index:
            issues.append(make_issue(
                idx, f"Statistical anomaly in '{col}'", "warning", "flagged", col,
                df.at[idx, col], None,
                f"Value unusually far from the typical range ({lower_bound:.1f} to {upper_bound:.1f})"
            ))
    return issues

# ---------- Part J: post-clean validation (proves the output is actually clean) ----------

def validate_clean_dataframe(df: pd.DataFrame, roles: dict, suggested_checks: list[dict] | None = None) -> tuple[bool, list[str]]:
    violations = []

    for col, role in roles.items():
        if role in ("identifier", "name", "quantity", "monetary") and df[col].isna().any():
            violations.append(f"{col}: {int(df[col].isna().sum())} missing required values remain")
        if role in ("quantity", "monetary") and pd.api.types.is_numeric_dtype(df[col]) and (df[col] < 0).any():
            violations.append(f"{col}: {int((df[col] < 0).sum())} negative values remain")

    if df.duplicated().any():
        violations.append(f"{int(df.duplicated().sum())} exact duplicate rows remain")

    if suggested_checks:
        ops = {
            "<=": lambda a, b: a > b, ">=": lambda a, b: a < b,
            "<": lambda a, b: a >= b, ">": lambda a, b: a <= b,
        }
        for check in suggested_checks:
            col_a, col_b, op = check.get("column_a"), check.get("column_b"), check.get("operator")
            if col_a in df.columns and col_b in df.columns and op in ops:
                if ops[op](df[col_a], df[col_b]).fillna(False).any():
                    violations.append(f"Business rule still violated: {col_a} {op} {col_b}")

    return (len(violations) == 0), violations

# ---------- Part K: the full pipeline ----------

def run_pipeline_universal(raw_df: pd.DataFrame, client=None, model: str = "gemini-2.5-pro",
                            fallback_suggested_checks: list[dict] | None = None):
    """
    fallback_suggested_checks: used ONLY when client is None — lets automated
    tests exercise the exact same rule-enforcement code path a live AI
    suggestion would use, without needing a live API key or network call.
    """
    working_df = raw_df.copy()
    all_issues = []

    # 1. Type inference
    working_df, column_types = infer_and_clean_types(working_df)

    # 2. Deduplication (structural — do first, before semantic analysis)
    working_df, dupes_removed, dedupe_method, dedupe_issues = deduplicate_universal(working_df)
    all_issues.extend(dedupe_issues)

    # 3. Categorical standardization (info-level, no removal)
    working_df, category_issues = standardize_categoricals_universal(working_df, column_types)
    all_issues.extend(category_issues)

    # 4. Schema inspection (ONE Gemini call; also drives semantic roles)
    if client is not None:
        schema_info = inspect_schema(working_df, column_types, client, model)
    else:
        schema_info = {"column_roles": {}, "suggested_checks": fallback_suggested_checks or []}

    roles = infer_semantic_roles(working_df, column_types, schema_info.get("column_roles"))

    # 5. Missing-value policy
    working_df, remove_mask_missing, missing_issues = handle_missing_values(working_df, roles)
    all_issues.extend(missing_issues)

    # 6. Deterministic domain rules (negative quantity/monetary)
    remove_mask_domain, domain_issues = detect_domain_violations(working_df, roles)
    all_issues.extend(domain_issues)

    # 7. AI-suggested business rules, validated then executed
    remove_mask_ai, ai_issues = validate_and_apply_ai_rules(working_df, schema_info.get("suggested_checks", []))
    all_issues.extend(ai_issues)

    # 8. Statistical anomalies — computed only on rows NOT already marked for
    #    removal, so a negative quantity doesn't also get double-reported as
    #    an outlier once it's already headed out via the domain rule.
    prelim_remove = remove_mask_missing | remove_mask_domain | remove_mask_ai
    anomaly_issues = detect_statistical_anomalies(working_df[~prelim_remove], column_types)
    all_issues.extend(anomaly_issues)

    # 9. Apply all removals together
    clean_df = working_df[~prelim_remove].copy()

    # 10. Post-clean validation — prove the output is actually clean
    validation_passed, remaining_violations = validate_clean_dataframe(
        clean_df, roles, schema_info.get("suggested_checks", [])
    )

    # 11. Build stats
    issues_df = pd.DataFrame(all_issues)
    error_issues = issues_df[issues_df["severity"] == "error"] if len(issues_df) else issues_df
    unique_rows_affected = int(error_issues["row_index"].nunique()) if len(error_issues) else 0

    stats = {
        "rows_before": len(raw_df),
        "rows_after": len(clean_df),
        "rows_removed": len(raw_df) - len(clean_df),
        "duplicates_removed": dupes_removed,
        "dedupe_method": dedupe_method,
        "total_issue_instances": len(issues_df),
        "unique_rows_affected": unique_rows_affected,
        "detected_column_types": column_types,
        "semantic_roles": roles,
        "ai_suggested_checks": schema_info.get("suggested_checks", []),
        "validation_passed": validation_passed,
        "remaining_violations": remaining_violations,
    }
    return clean_df, issues_df, stats, schema_info